### ISSUE TITLE
希望能够考虑更新

### ISSUE THREAD

**Issue by wuwo020** [koishijs/koishi-plugin-rss#2]
各位老大们，有空考虑更新一下这个插件不？
这个库太老了！
目前除了rss.app的自制源，其他的内容应该都无法再发送出来了
rss还是很有用的！

**Comment by ilharp** [comment]
刚刚经过测试，该插件完全可用。请问不可用订阅的订阅 url 能否给出一个示例？发生问题时有无报错？直接在浏览器中访问 url 是否可以正确获取到数据？

如果可以给出 url 示例和报错日志的话，可以直接在此回复并 reopen。
