### ISSUE TITLE
这个插件不更新么？

### ISSUE THREAD

**Issue by Ra-charles** [koishijs/koishi-plugin-rss#3]
好像出问题蛮久了，偶尔能工作一下，QQ群的能发一点点的信息，频道直接就一点反应没有了，也不报错也不报警告的，希望有大佬修下

**Comment by ilharp** [comment]
刚刚经过测试，该插件完全可用。请问不可用订阅的订阅 url 能否给出一个示例？发生问题时有无报错？直接在浏览器中访问 url 是否可以正确获取到数据？

如果可以给出 url 示例和报错日志的话，可以直接在此回复并 reopen。
