### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by MCBBC** [koishijs/koishi-plugin-rss#4]
Koishi版本：4.11.1
平台：Windows
症状：在插件市场安装完毕后，插件市场提示安装成功，但是插件列表里面提示未安装该插件（有rss的插件选项，但是点击会在配置页面最上方显示未安装该插件）

**Comment by MCBBC** [comment]
日志里面显示 Error: Cannot find module 'aws4'

**Comment by MirrorCY** [comment]
经测试目前已不存在此问题，如果有复现请随时重新开启此 issue。
